#' Safely Load and Detect Audio File Formats
#'
#' @description Reads raw audio files (.wav or .mp3) from disk into R memory,
#' automatically detecting the format and handling decompression safely.
#'
#' @param file_path Character string. The absolute or relative path to the audio file.
#'
#' @details
#' Field recordings often come in varying formats. This function acts as a wrapper
#' around the \code{tuneR} package's reading capabilities. It parses the file extension,
#' routes the file to the correct decoding engine (\code{readMP3} or \code{readWave}),
#' and provides explicit error handling if the file is corrupted or unsupported.
#'
#' @return A \code{Wave} object containing the binary audio data.
#'
#' @seealso \code{\link{standardize_audio}}, \code{\link{extract_clean_chunks}}
#'
#' @examples
#' \dontrun{
#' # Load a local MP3 field recording
#' macaw_audio <- read_audio_file("data-raw/audio/ara_macao_01.mp3")
#'
#' # Load a WAV file
#' owl_audio <- read_audio_file("data-raw/audio/bubo_bubo_01.wav")
#' }
#' @export
read_audio_file <- function(file_path) {
  if (!file.exists(file_path)) stop("File not found:", file_path)

  ext <- tolower(tools::file_ext(file_path))
  if (ext == "mp3") {
    tryCatch({
      wave <- tuneR::readMP3(file_path)
      cat("[OK] MP3 loaded\n")
      return(wave)
    }, error = function(e) { stop("Error reading MP3:", e$message) })
  } else if (ext == "wav") {
    tryCatch({
      wave <- tuneR::readWave(file_path)
      cat("[OK] WAV loaded\n")
      return(wave)
    }, error = function(e) { stop("Error reading WAV:", e$message) })
  } else {
    stop("Unsupported format. Use .mp3 or .wav")
  }
}

#' Standardize Audio Properties for Feature Extraction
#'
#' @description Normalizes audio structures by verifying object integrity, forcing stereo channels into mono, standardizing the sample rate, and normalizing bit-depth.
#'
#' @param wave A \code{Wave} object generated by the \code{tuneR} package.
#' @param target_rate Integer. The target sample rate in Hz (default: 22050).
#'
#' @details
#' Mathematical feature extraction requires strictly uniform input data to prevent matrix dimension errors and scale skews. This function performs a 4-step standardization:
#' 1. Validates that the input is a non-empty \code{Wave} object.
#' 2. Forcefully converts stereo recordings into mono by isolating the left channel.
#' 3. Downsamples audio to the \code{target_rate} to ensure dimensional consistency. Warns if the audio is already below the target rate.
#' 4. Normalizes the amplitude to a standard 16-bit scale so volume differences don't skew the machine learning model.
#'
#' @return A standardized \code{Wave} object ready for Digital Signal Processing.
#'
#' @examples
#' \dontrun{
#' raw_wave <- read_audio_file("data-raw/audio/loud_bird.wav")
#'
#' # Standardize to Mono, 22050 Hz, and 16-bit amplitude
#' clean_wave <- standardize_audio(raw_wave)
#'
#' # Verify properties
#' print(clean_wave@stereo) # FALSE
#' print(clean_wave@samp.rate) # 22050
#' print(clean_wave@bit) # 16
#' }
#' @export
standardize_audio <- function(wave, target_rate = 22050) {

  # 1. Input Validation: Check object type and integrity
  if (!inherits(wave, "Wave")) {
    stop("Input error: Expected a 'Wave' object, but received something else.")
  }

  if (length(wave@left) == 0) {
    warning("Audio standardization warning: The Wave object contains 0 audio samples.")
    return(wave)
  }

  # 2. Stereo to Mono Conversion
  if (wave@stereo) {
    wave <- tryCatch({
      tuneR::mono(wave, "left")
    }, error = function(e) {
      warning("Failed to convert stereo to mono. Error: ", e$message)
      return(wave)
    })
  }

  # 3. Sample Rate Standardization
  if (wave@samp.rate > target_rate) {
    wave <- tryCatch({
      tuneR::downsample(wave, target_rate)
    }, error = function(e) {
      warning(sprintf("Failed to downsample to %d Hz. Error: %s", target_rate, e$message))
      return(wave)
    })
  } else if (wave@samp.rate < target_rate) {
    # We warn instead of crashing, as some algorithms can still handle it,
    # but the user needs to know their high-frequency data is missing.
    warning(sprintf(
      "Audio sample rate (%d Hz) is lower than target (%d Hz). High-frequency features may be distorted.",
      wave@samp.rate, target_rate
    ))
  }

  # 4. Bit-Depth / Amplitude Normalization
  # This scales the wave to a standard 16-bit format, ensuring loud recordings
  # and quiet recordings are evaluated equally by the model.
  wave <- tryCatch({
    tuneR::normalize(wave, unit = "16", pcm = TRUE)
  }, error = function(e) {
    return(wave) # Fails safe if already normalized or weird format
  })

  return(wave)
}

#' Plot Bird Audio Waveform and Spectrogram
#'
#' @description Generates a dual-pane visualization showing both the physical
#' amplitude waveform and the frequency spectrogram of an acoustic sample.
#'
#' @param wave_obj A \code{Wave} object loaded via \code{tuneR}.
#' @param title Character string. The main title for the plotted visual
#' (default: "Bird Audio Profile").
#'
#' @details
#' This function is highly useful for visually inspecting the quality of a recording
#' before running it through the machine learning pipeline. The top pane displays
#' an oscillogram (amplitude over time) to spot volume spikes, while the bottom
#' pane plots a spectrogram (frequency over time) using the \code{seewave} package
#' to reveal the bird's vocal harmonic structure.
#'
#' @examples
#' \dontrun{
#' wave <- read_audio_file("data-raw/audio/nightingale.wav")
#' wave <- standardize_audio(wave)
#'
#' # Generate the dual-pane visualization
#' plot_bird_audio(wave, title = "Common Nightingale Analysis")
#' }
#' @export
plot_bird_audio <- function(wave_obj, title = "Bird Audio Profile") {
  # Save original graphical parameters safely
  oldpar <- par(no.readonly = TRUE)
  on.exit(par(oldpar))

  # Set up a clean 2-row layout
  par(mfrow = c(2, 1), mar = c(4, 4, 2, 1))

  # 1. Plot the physical waveform (Amplitude over time)
  seewave::oscillo(wave_obj, f = wave_obj@samp.rate, title = FALSE)
  title(main = paste(title, "- Waveform"))

  # 2. Plot the Spectrogram (Frequency over time)
  seewave::spectro(wave_obj, f = wave_obj@samp.rate, collevels = seq(-40, 0, 0.5),
                   palette = seewave::spectro.colors, scale = FALSE,
                   main = paste(title, "- Spectrogram"))
}

#' Extract Active Acoustic Chunks from Audio
#'
#' @description Performs Voice Activity Detection (VAD) to isolate active bird
#' vocalizations from an audio file or \code{Wave} object, discarding background
#' noise and pure silence.
#'
#' @param audio_input A character string (path to the MP3/WAV file) OR an
#' already loaded \code{Wave} object.
#' @param primary_min_sec Numeric. The target minimum duration (in seconds) for
#' a valid acoustic chunk (default: 0.4).
#' @param fallback_min_sec Numeric. The backup minimum duration if no primary chunks
#' are found, accommodating shorter chirps (default: 0.1).
#' @param max_duration_sec Numeric. A memory-protection limit; skips files longer
#' than this duration (default: 180 seconds).
#'
#' @details
#' Raw field recordings contain massive amounts of silence, wind, and background noise.
#' Feeding this raw audio into a feature extractor dilutes mathematical averages,
#' destroying accuracy.
#'
#' This function acts polymorphically. If given a file path, it safely loads the audio.
#' If given a Shiny uploaded \code{Wave} object, it processes it immediately.
#'
#' \strong{Pipeline:}
#' \enumerate{
#'   \item \strong{Filtering:} Applies a 150 Hz high-pass filter to strip wind rumble.
#'   \item \strong{Detection:} Uses amplitude thresholding to find timestamps of vocal energy spikes.
#'   \item \strong{Extraction:} Slices the audio at those timestamps, returning pure \code{Wave} objects.
#' }
#'
#' @return A list of isolated \code{Wave} objects containing only active bird calls.
#'
#' @examples
#' \dontrun{
#' # Example 1: Pass a direct file path (Batch Processing Mode)
#' chunks <- extract_clean_chunks("data-raw/audio/long_field_recording.mp3")
#'
#' # Example 2: Pass an already loaded Wave object (Shiny Live Inference Mode)
#' live_wave <- read_audio_file("data-raw/audio/live_upload.wav")
#' live_chunks <- extract_clean_chunks(live_wave)
#'
#' # Check how many vocalizations were found
#' print(length(live_chunks))
#'
#' # Access the best chunk
#' best_chunk <- live_chunks[]
#' }
#' @export
extract_clean_chunks <- function(audio_input, primary_min_sec = 0.4, fallback_min_sec = 0.1, max_duration_sec = 180) {

  # =========================================================
  # 1. POLYMORPHIC INPUT HANDLING: File Path or Wave Object?
  # =========================================================
  if (inherits(audio_input, "Wave")) {
    wave <- audio_input
  } else if (is.character(audio_input) && file.exists(audio_input)) {
    ext <- tolower(tools::file_ext(audio_input))
    wave <- tryCatch({
      if (ext == "mp3") {
        tuneR::readMP3(audio_input)
      } else if (ext == "wav") {
        tuneR::readWave(audio_input)
      } else {
        NULL
      }
    }, error = function(e) NULL)
  } else {
    cat("[X] Invalid Input: Must be a Wave object or a valid file path.\n")
    return(list())
  }

  if (is.null(wave)) {
    cat("[X] Corrupted or Unreadable Audio\n")
    return(list())
  }

  # =========================================================
  # 2. DURATION CHECK & STANDARDIZATION
  # =========================================================
  duration_sec <- length(wave@left) / wave@samp.rate

  # Only print console logging if it came from a file path (Batch processing mode)
  if (is.character(audio_input)) {
    cat(sprintf("[Length: %.1f sec] ", duration_sec))
    if (duration_sec > max_duration_sec) {
      cat("! SKIPPED: Audio is too long.\n")
      return(list())
    } else {
      cat("[OK] Processing...\n")
    }
  } else {
    # If in Shiny live-inference mode, just fail silently if too long
    if (duration_sec > max_duration_sec) return(list())
  }

  # Prevent VAD crashes from weird sample rates
  if (wave@stereo) wave <- tuneR::mono(wave, "left")
  if (wave@samp.rate != 22050) {
    wave <- tryCatch(tuneR::downsample(wave, 22050), error = function(e) wave)
  }

  # =========================================================
  # 3. NOISE FILTERING & VAD ALGORITHM
  # =========================================================
  filtered_wave <- tryCatch({
    seewave::fir(wave, f = wave@samp.rate, from = 150, bandpass = FALSE, output = "Wave")
  }, error = function(e) wave)

  if (is.null(filtered_wave)) return(list(wave))

  timing <- tryCatch({
    seewave::timer(filtered_wave, f = filtered_wave@samp.rate, threshold = 5,
                   msmooth = c(500, 0), plot = FALSE)
  }, error = function(e) NULL)

  if (is.null(timing) || length(timing$s.start) == 0) return(list(wave))

  # =========================================================
  # 4. CHUNK EXTRACTION
  # =========================================================
  clean_chunks <- list()

  # Phase 1: Strict Extraction
  for (i in seq_along(timing$s.start)) {
    duration <- timing$s.end[i] - timing$s.start[i]
    if (duration >= primary_min_sec) {
      chunk <- tuneR::extractWave(wave, from = timing$s.start[i], to = timing$s.end[i], xunit = "time")
      clean_chunks[[length(clean_chunks) + 1]] <- chunk
    }
  }

  # Phase 2: Dynamic Fallback
  if (length(clean_chunks) == 0) {
    for (i in seq_along(timing$s.start)) {
      duration <- timing$s.end[i] - timing$s.start[i]
      if (duration >= fallback_min_sec) {
        chunk <- tuneR::extractWave(wave, from = timing$s.start[i], to = timing$s.end[i], xunit = "time")
        clean_chunks[[length(clean_chunks) + 1]] <- chunk
      }
    }
  }

  # If chunks still fail, return empty list to signal no valid chunks found
  if (length(clean_chunks) == 0) return(list())

  return(clean_chunks)
}
